import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import SideNavbar from '../src/components/side_navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={`containerGrid ${styles.home}`}>
      <Head>
        <title>Talk Your Mind - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
        <SideNavbar/>

      </div>

      
    </div>
  )
}

export default Home
