import { HomeIcon } from '@heroicons/react/outline'
import { Breadcrumbs, Link, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState} from 'react'
import { Navbar } from '../src/components/navbar'
import SideNavbar from '../src/components/side_navbar'
import UsersTable from '../src/components/users_table'
import { useStateValue } from '../src/state_manger/contextApi'
import {PlusIcon, TrashIcon} from '@heroicons/react/outline'
import styles from '../styles/Home.module.css'
import { USER_LOGIN } from '../src/state_manger/constants'

const Users: NextPage = () => {

  const {state, dispatch} = useStateValue();
  const router = useRouter();
  const [pageLoading, setPageLoading] = useState(true);

  useEffect(()=>{
    if(!state.user){
      const user = localStorage.getItem("user");
      if(user){
        let userJson = JSON.parse(user);
        dispatch({type : USER_LOGIN, payload : userJson})
      }else{
        router.push("/auth")
      }
    }else{
      setPageLoading(false)
    }
  },[router, state.user, dispatch]);


  if(pageLoading) return <div>Loading....</div>

  return (
    <div className={`containerGrid ${styles.home}`}>
      <Head>
        <title>Talk Your Mind - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div style={{display : "flex"}}>
        <SideNavbar/>
       
        <div style={{width : "100%"}}>
          <Navbar/>

          <div style={{width : "100%", padding : "2rem"}}>


            {/* BREAD CRUMBS ======  NAV LINKS */}
            <div className={`containerFlex ${styles.breadcrumbs_cont}`}>
              <Breadcrumbs aria-label="breadcrumb">

                <Link underline="hover" color="inherit" href="/">
                  <HomeIcon/>
                </Link>

                <Link underline="hover" color="inherit" href="/">
                  SYSTEM
                </Link>

                <Link
                  underline="hover"
                  color="inherit"
                  href="/users"
                >
                  Users
                </Link>

                <Typography color="text.primary">Users</Typography>
              </Breadcrumbs>




              <div>
                <div  style={{width : "100px", height : "10px", background : "red"}}>

                </div>
                <div  style={{width : "100px", height : "10px", background : "red"}}>

                </div>
              </div>
            </div>


            <div className={styles.add_delete_user_cont}>
                <button style = {{backgroundColor : "var(--black)", color : 'white'}}>
                    <PlusIcon height={15} /> Create New USer
                </button>

                <button style = {{backgroundColor : "red", color : 'white'}} >
                  <TrashIcon height={15} /> Delet User
                </button>
            </div>

            <UsersTable/>

          </div>
        </div>

      </div>

      
    </div>
  )
}

export default Users
